#include "conformer.h"
#include "descriptors.h"
#include "peptide.h"

#ifdef __EMSCRIPTEN__
#include <emscripten/bind.h>
using namespace emscripten;
using namespace nanopeptide;

// Wrapper to return PDB string directly
std::string generatePDB(const std::string& sequence, int ss_type) {
    SecondaryStructure ss;
    switch (ss_type) {
        case 0: ss = SecondaryStructure::Helix; break;
        case 1: ss = SecondaryStructure::Sheet; break;
        default: ss = SecondaryStructure::Coil; break;
    }
    auto atoms = generate_backbone(sequence, ss);
    return atoms_to_pdb(atoms, "Generated by nano-peptide WASM core");
}

// Wrapper for properties that returns a JS-friendly object
val computeProperties(const std::string& sequence) {
    auto props = compute_properties(sequence);
    val result = val::object();
    result.set("length", props.length);
    result.set("molecularWeight", props.molecular_weight);
    result.set("netCharge", props.net_charge);
    result.set("isoelectricPoint", props.isoelectric_point);
    result.set("gravy", props.gravy);
    result.set("instabilityIndex", props.instability_index);
    result.set("isStable", props.is_stable);

    val comp = val::object();
    for (auto& [key, count] : props.composition) {
        comp.set(std::string(1, key), count);
    }
    result.set("composition", comp);
    return result;
}

// Backbone angles for Ramachandran
val getBackboneAngles(const std::string& sequence, int ss_type) {
    SecondaryStructure ss;
    switch (ss_type) {
        case 0: ss = SecondaryStructure::Helix; break;
        case 1: ss = SecondaryStructure::Sheet; break;
        default: ss = SecondaryStructure::Coil; break;
    }
    auto atoms = generate_backbone(sequence, ss);
    auto angles = extract_angles(atoms);

    val result = val::array();
    for (size_t i = 0; i < angles.size(); i++) {
        val a = val::object();
        a.set("residueIndex", angles[i].residue_index);
        a.set("residue", std::string(1, angles[i].residue_code));
        a.set("phi", std::isnan(angles[i].phi) ? val::null() : val(angles[i].phi));
        a.set("psi", std::isnan(angles[i].psi) ? val::null() : val(angles[i].psi));
        result.call<void>("push", a);
    }
    return result;
}

EMSCRIPTEN_BINDINGS(peptide_core) {
    function("generatePDB", &generatePDB);
    function("computeProperties", &computeProperties);
    function("getBackboneAngles", &getBackboneAngles);
}
#endif
