/**
 * Generate idealized PDB coordinates for a peptide sequence.
 * Uses standard backbone geometry (phi=-57, psi=-47 for alpha helix as default).
 * This is a simplified generator for visualization — real structure prediction
 * would use ESMFold/AlphaFold.
 */

const RESIDUE_MAP: Record<string, string> = {
  A: 'ALA', R: 'ARG', N: 'ASN', D: 'ASP', C: 'CYS',
  E: 'GLU', Q: 'GLN', G: 'GLY', H: 'HIS', I: 'ILE',
  L: 'LEU', K: 'LYS', M: 'MET', F: 'PHE', P: 'PRO',
  S: 'SER', T: 'THR', W: 'TRP', Y: 'TYR', V: 'VAL',
}

// Standard bond lengths (Angstroms) and angles
const N_CA = 1.458
const CA_C = 1.523
const C_N = 1.329
const C_O = 1.231
const CA_CB = 1.521

// Standard bond angles (radians)
const N_CA_C = (111.2 * Math.PI) / 180
const CA_C_N = (116.2 * Math.PI) / 180
const C_N_CA = (121.7 * Math.PI) / 180
const CA_C_O = (120.8 * Math.PI) / 180

type Vec3 = [number, number, number]

function normalize(v: Vec3): Vec3 {
  const len = Math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)
  return [v[0] / len, v[1] / len, v[2] / len]
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ]
}

function add(a: Vec3, b: Vec3): Vec3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

function sub(a: Vec3, b: Vec3): Vec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
}

function scale(v: Vec3, s: number): Vec3 {
  return [v[0] * s, v[1] * s, v[2] * s]
}

/**
 * Place a new atom given three reference atoms and geometry parameters.
 * Uses the Nerf algorithm (Natural Extension Reference Frame).
 */
function placeAtom(
  a: Vec3, b: Vec3, c: Vec3,
  bondLength: number, bondAngle: number, dihedral: number
): Vec3 {
  const bc = normalize(sub(c, b))
  const ab = normalize(sub(b, a))
  const n = normalize(cross(ab, bc))
  const nbc = cross(n, bc)

  const d = bondLength
  const theta = Math.PI - bondAngle
  const chi = dihedral

  const dx = d * Math.cos(theta)
  const dy = d * Math.sin(theta) * Math.cos(chi)
  const dz = d * Math.sin(theta) * Math.sin(chi)

  return add(c, add(scale(bc, dx), add(scale(nbc, dy), scale(n, dz))))
}

export type SecondaryStructure = 'helix' | 'sheet' | 'coil'

const SS_ANGLES: Record<SecondaryStructure, [number, number]> = {
  helix: [(-57 * Math.PI) / 180, (-47 * Math.PI) / 180],
  sheet: [(-119 * Math.PI) / 180, (113 * Math.PI) / 180],
  coil: [(-65 * Math.PI) / 180, (-40 * Math.PI) / 180],
}

export function generatePDB(
  sequence: string,
  structure: SecondaryStructure = 'helix'
): string {
  const residues = sequence.toUpperCase().split('').filter(c => c in RESIDUE_MAP)
  if (residues.length === 0) return ''

  const [phi, psi] = SS_ANGLES[structure]
  const omega = Math.PI // trans peptide bond

  const atoms: { name: string; resName: string; resSeq: number; x: number; y: number; z: number; element: string }[] = []

  // Seed atoms for NeRF placement
  let prevC: Vec3 = [-1.0, 0.0, 0.0]
  let prevCA: Vec3 = [0.0, 0.0, 0.0]
  let prevN: Vec3 = [N_CA * Math.cos(Math.PI - C_N_CA), N_CA * Math.sin(Math.PI - C_N_CA), 0.0]

  // Actually let's use a simpler initial placement
  prevN = [0.0, 0.0, 0.0]
  prevCA = [N_CA, 0.0, 0.0]
  prevC = placeAtom(prevN, prevCA, [prevCA[0], prevCA[1] + 1, prevCA[2]], CA_C, N_CA_C, 0)

  let atomSerial = 1

  for (let i = 0; i < residues.length; i++) {
    const resName = RESIDUE_MAP[residues[i]]
    const resSeq = i + 1

    let N: Vec3, CA: Vec3, C: Vec3, O: Vec3

    if (i === 0) {
      N = prevN
      CA = prevCA
      C = prevC
    } else {
      // Place N from previous C
      N = placeAtom(prevCA, prevC, prevC, C_N, CA_C_N, psi)
      // Place CA from N
      CA = placeAtom(prevC, N, N, N_CA, C_N_CA, omega)
      // Place C from CA
      C = placeAtom(N, CA, CA, CA_C, N_CA_C, phi)
    }

    // Place O
    O = placeAtom(CA, C, C, C_O, CA_C_O, Math.PI)

    atoms.push({ name: 'N', resName, resSeq, x: N[0], y: N[1], z: N[2], element: 'N' })
    atoms.push({ name: 'CA', resName, resSeq, x: CA[0], y: CA[1], z: CA[2], element: 'C' })
    atoms.push({ name: 'C', resName, resSeq, x: C[0], y: C[1], z: C[2], element: 'C' })
    atoms.push({ name: 'O', resName, resSeq, x: O[0], y: O[1], z: O[2], element: 'O' })

    // Place CB for non-glycine residues
    if (residues[i] !== 'G') {
      const CB = placeAtom(N, CA, C, CA_CB, N_CA_C, (122.0 * Math.PI) / 180)
      atoms.push({ name: 'CB', resName, resSeq, x: CB[0], y: CB[1], z: CB[2], element: 'C' })
    }

    prevN = N
    prevCA = CA
    prevC = C
    atomSerial += residues[i] === 'G' ? 4 : 5
  }

  // Format as PDB
  const lines: string[] = [
    'HEADER    PEPTIDE                                 18-MAR-26   NANO',
    `TITLE     IDEALIZED ${structure.toUpperCase()} STRUCTURE`,
    `REMARK   1 GENERATED BY NANO-PEPTIDE`,
    `REMARK   2 SEQUENCE: ${sequence}`,
  ]

  atomSerial = 1
  for (const atom of atoms) {
    const serial = String(atomSerial++).padStart(5)
    const name = atom.name.length < 4 ? ` ${atom.name.padEnd(3)}` : atom.name.padEnd(4)
    const resName = atom.resName.padEnd(3)
    const chain = 'A'
    const resSeq = String(atom.resSeq).padStart(4)
    const x = atom.x.toFixed(3).padStart(8)
    const y = atom.y.toFixed(3).padStart(8)
    const z = atom.z.toFixed(3).padStart(8)
    const occ = '  1.00'
    const bfac = '  0.00'
    const element = atom.element.padStart(2)

    lines.push(`ATOM  ${serial} ${name} ${resName} ${chain}${resSeq}    ${x}${y}${z}${occ}${bfac}          ${element}`)
  }

  lines.push('END')
  return lines.join('\n')
}

/**
 * Extract backbone phi/psi angles from generated coordinates.
 * Returns array of { residue, phi, psi } for Ramachandran plot.
 */
export interface BackboneAngles {
  residue: string
  resIndex: number
  phi: number | null
  psi: number | null
}

export function extractBackboneAngles(pdbData: string): BackboneAngles[] {
  const atoms: { name: string; resSeq: number; resName: string; coords: Vec3 }[] = []

  for (const line of pdbData.split('\n')) {
    if (!line.startsWith('ATOM')) continue
    const name = line.substring(12, 16).trim()
    if (!['N', 'CA', 'C'].includes(name)) continue
    const resSeq = parseInt(line.substring(22, 26))
    const resName = line.substring(17, 20).trim()
    const x = parseFloat(line.substring(30, 38))
    const y = parseFloat(line.substring(38, 46))
    const z = parseFloat(line.substring(46, 54))
    atoms.push({ name, resSeq, resName, coords: [x, y, z] })
  }

  // Group by residue
  const residueMap = new Map<number, Map<string, Vec3>>()
  const resNames = new Map<number, string>()
  for (const atom of atoms) {
    if (!residueMap.has(atom.resSeq)) residueMap.set(atom.resSeq, new Map())
    residueMap.get(atom.resSeq)!.set(atom.name, atom.coords)
    resNames.set(atom.resSeq, atom.resName)
  }

  const resIndices = [...residueMap.keys()].sort((a, b) => a - b)
  const result: BackboneAngles[] = []

  for (let i = 0; i < resIndices.length; i++) {
    const idx = resIndices[i]
    const current = residueMap.get(idx)!
    const prev = i > 0 ? residueMap.get(resIndices[i - 1])! : null
    const next = i < resIndices.length - 1 ? residueMap.get(resIndices[i + 1])! : null

    let phi: number | null = null
    let psi: number | null = null

    if (prev && prev.has('C') && current.has('N') && current.has('CA') && current.has('C')) {
      phi = dihedral(prev.get('C')!, current.get('N')!, current.get('CA')!, current.get('C')!)
    }
    if (next && current.has('N') && current.has('CA') && current.has('C') && next.has('N')) {
      psi = dihedral(current.get('N')!, current.get('CA')!, current.get('C')!, next.get('N')!)
    }

    const code3 = resNames.get(idx) || 'UNK'
    const code1 = Object.entries(RESIDUE_MAP).find(([, v]) => v === code3)?.[0] || '?'

    result.push({ residue: code1, resIndex: i, phi, psi })
  }

  return result
}

function dihedral(a: Vec3, b: Vec3, c: Vec3, d: Vec3): number {
  const b1 = sub(b, a)
  const b2 = sub(c, b)
  const b3 = sub(d, c)

  const n1 = cross(b1, b2)
  const n2 = cross(b2, b3)

  const m1 = cross(n1, normalize(b2))

  const x = dot(n1, n2)
  const y = dot(m1, n2)

  return (Math.atan2(y, x) * 180) / Math.PI
}

function dot(a: Vec3, b: Vec3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}
